# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Matt Motoki
email: 
description: >-
  Matt Motoki 3.0
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mattmotoki.github.io" # the base hostname & protocol for your site
twitter_username: mattmotoki
github_username:  mattmotoki
google_analytics: G-9PREHWYS4F

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# Collections
collections:
  projects:
    output: true
  competitions:
    output: true
  art:
    output: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - archive
  - README.md

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:title/
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "competitions"
    values:
      layout: "competition"
  - scope:
      path: ""
      type: "art"
    values:
      layout: "art"
      visible: true
      priority: 999
      # display_image defaults to image if not specified
      # tagline defaults to title if not specified
      # priority: controls the order (lower numbers first, unspecified priority shows last)
  - scope:
      path: ""
    values:
      layout: "default"
