name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      
      - name: Install dependencies
        run: bundle install
      
      - name: Build site
        env:
          GOOGLE_ANALYTICS_ID: ${{ github.ref == 'refs/heads/main' && secrets.GOOGLE_ANALYTICS_ID || '' }}
        run: JEKYLL_ENV=${{ github.ref == 'refs/heads/main' && 'production' || 'development' }} bundle exec jekyll build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site 